# Generated by Django 4.0.3 on 2022-11-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hot',
            field=models.IntegerField(default=1),
        ),
    ]
