# Generated by Django 4.0.3 on 2022-11-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0001_initial'),
        ('article', '0005_alter_article_classifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='classifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifications.classifications'),
        ),
    ]
